### ISSUE TITLE
Implement Careers link

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt.web#11]
We would like to add a link to "Careers".

This involves selecting a job platform, creating one or more job descriptions, adding them to the platform, and linking to it.

**Comment by JosephVoid** [comment]
I'm on it.

**Comment by abrichr** [comment]
Hi @JosephVoid , thank you for your interest! I see you've expressed interest in https://github.com/OpenAdaptAI/OpenAdapt.web/issues/37 as well. I'll close this as completed since we have a link in the footer to the relevant README section.
