### ISSUE TITLE
Add "Download for Mac/Win" button

### ISSUE THREAD

**Issue by abrichr** [OpenAdaptAI/OpenAdapt.web#46]
We want to make it extremely easy for visitors to openadapt.ai to download and install the OpenAdapt client software.

This task will be complete when there is a big "Download" button that lets users download the client software for their operating system.

This should be downloaded from the automatically built releases (see https://github.com/OpenAdaptAI/OpenAdapt/issues/574).

**Comment by kiarashgb11** [comment]
I will be doing a pull request for this issue.

**Comment by abrichr** [comment]
Implemented in https://github.com/OpenAdaptAI/OpenAdapt.web/pull/53
